// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: daily.proto

package grpc.one.dailyfarm;

public final class DemoDailyFarmImplementation {
  private DemoDailyFarmImplementation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dailyFarm_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dailyFarm_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dailyFarm_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dailyFarm_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013daily.proto\022\tdailyFarm\"\036\n\014HelloRequest" +
      "\022\016\n\006myname\030\001 \001(\t\"\037\n\nHelloReply\022\021\n\tmymess" +
      "age\030\001 \001(\t2G\n\007Greeter\022<\n\010SayHello\022\027.daily" +
      "Farm.HelloRequest\032\025.dailyFarm.HelloReply" +
      "\"\000B3\n\022grpc.one.dailyfarmB\033DemoDailyFarmI" +
      "mplementationP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_dailyFarm_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dailyFarm_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dailyFarm_HelloRequest_descriptor,
        new java.lang.String[] { "Myname", });
    internal_static_dailyFarm_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dailyFarm_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dailyFarm_HelloReply_descriptor,
        new java.lang.String[] { "Mymessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
