// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: daily.proto

package grpc.one.dailyfarm;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dailyFarm.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mymessage = 1;</code>
   */
  java.lang.String getMymessage();
  /**
   * <code>string mymessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getMymessageBytes();
}
