// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: daily.proto

package grpc.one.dailyfarm;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dailyFarm.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string myname = 1;</code>
   */
  java.lang.String getMyname();
  /**
   * <code>string myname = 1;</code>
   */
  com.google.protobuf.ByteString
      getMynameBytes();
}
